[package]
name = "gan"
version = "0.1.0"
authors = ["thibault.serabian <thibault.serabian@epita.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
brain = {path="../brain"}
rand = '0.8.4'