[package]
name = "brain"
version = "0.1.0"
authors = ["thibault.serabian <thibault.serabian@epita.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graph = {path = "../graph"}
rand="0.8.3"